#!/usr/bin/env bash
## This file is used for the Zappy tournament

PYTHON_MAIN=$(realpath $(dirname "$0"))/../zappy_ai

if ! [ -f $PYTHON_MAIN ]; then
    echo "$PYTHON_MAIN couldn't be found, try running \`make\`"
    exit 1
fi

exec "python3" "$PYTHON_MAIN" "$@"
